options:
  dnn:
    type: string
    default: internet
    description: Data Network Name (DNN)
  gnb-subnet:
    type: string
    default: 192.168.251.0/24
    description: gNodeB subnet.
  core-interface:
    type: string
    description: Interface on the host to use for the Core Network.
  core-ip:
    type: string
    default: 192.168.250.3/24
    description: IP address used by the UPF's Core interface.
  core-gateway-ip:
    type: string
    default: 192.168.250.1
    description: Gateway IP address to the Core Network.
  access-interface:
    type: string
    description: Interface on the host to use for the Access Network.
  access-ip:
    type: string
    default: 192.168.252.3/24
    description: IP address used by the UPF's Access interface.
  access-gateway-ip:
    type: string
    default: 192.168.252.1
    description: Gateway IP address to the Access Network.
  external-upf-hostname:
    type: string
    description: |-
      Externally accessible FQDN for the UPF.
      If not provided, it will default to the LoadBalancer Service hostname. 
      If that is not available, it will default to the internal
      Kubernetes FQDN of the service.
