options:
  upf-mode:
    type: string
    default: af_packet
    description: |
      Either `af_packet` (default) or `dpdk`.
  dnn:
    type: string
    default: internet
    description: Data Network Name (DNN)
  gnb-subnet:
    type: string
    default: 192.168.251.0/24
    description: gNodeB subnet.
  access-interface:
    type: string
    description: Interface on the host to use for the Access Network.
  access-interface-mac-address:
    type: string
    description: |
      MAC address of the UPF's Access interface. 
      Required only if `upf-mode` is `dpdk`.
  access-ip:
    type: string
    default: 192.168.252.3/24
    description: IP address used by the UPF's Access interface.
  access-gateway-ip:
    type: string
    default: 192.168.252.1
    description: Gateway IP address to the Access Network.
  access-interface-mtu-size:
    type: int
    description: |
      MTU for the access interface (1200 <= MTU <= 65535) in bytes.
      If not specified, Multus will use its default value (typically 1500).
  core-interface:
    type: string
    description: Interface on the host to use for the Core Network.
  core-interface-mac-address:
    type: string
    description: |
      MAC address of the UPF's Core interface. 
      Required only if `upf-mode` is `dpdk`.
  core-ip:
    type: string
    default: 192.168.250.3/24
    description: IP address used by the UPF's Core interface.
  core-gateway-ip:
    type: string
    default: 192.168.250.1
    description: Gateway IP address to the Core Network.
  core-interface-mtu-size:
    type: int
    description: |
      MTU for the core interface (1200 <= MTU <= 65535) in bytes.
      If not specified, Multus will use its default value (typically 1500).
  external-upf-hostname:
    type: string
    description: |
      Externally accessible FQDN for the UPF.
      If not provided, it will default to the LoadBalancer Service hostname. 
      If that is not available, it will default to the internal
      Kubernetes FQDN of the service.
  enable-hugepages:
    type: boolean
    default: false
    description: |
      When enabled, HugePages of 1Gi will be used for a total of 2Gi HugePages.
      HugePages must be enabled if `upf-mode` is `dpdk`.
  enable-hw-checksum:
    type: boolean
    default: false
    description: |
      When enabled, hardware checksum will be used on the network interfaces.
      Only has an effect when `upf-mode` is `dpdk` and must be supported by
      the hardware.
