name: Main branch CI

on:
  pull_request:
    branches:
      - main
  push:
  schedule:
    - cron: '20 7 * * 0'

jobs:
  check-libraries:
    uses: canonical/sdcore-github-workflows/.github/workflows/check-libraries.yaml@main
    secrets: inherit

  lint-report:
    uses: canonical/sdcore-github-workflows/.github/workflows/lint-report.yaml@main

  static-analysis:
    uses: canonical/sdcore-github-workflows/.github/workflows/static-analysis.yaml@main

  terraform-check:
    uses: canonical/sdcore-github-workflows/.github/workflows/terraform.yaml@main

  unit-tests-with-coverage:
    uses: canonical/sdcore-github-workflows/.github/workflows/unit-test.yaml@main

  integration-test:
    uses: canonical/sdcore-github-workflows/.github/workflows/integration-test-with-multus.yaml@main
    with:
      charm-file-name: "sdcore-upf-k8s_ubuntu-22.04-amd64.charm"

  publish-charm:
    name: Publish Charm
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
      - integration-test
    if: ${{ github.ref_name == 'main' }}
    uses: canonical/sdcore-github-workflows/.github/workflows/publish-charm.yaml@main
    with:
      charm-file-name: "sdcore-upf-k8s_ubuntu-22.04-amd64.charm"
      track-name: 1.3
    secrets: inherit

  fiveg-n3-lib-needs-publishing:
    runs-on: ubuntu-22.04
    outputs:
      needs-publishing: ${{ steps.changes.outputs.fiveg_n3 }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            fiveg_n3:
              - 'lib/charms/sdcore_upf_k8s/v0/fiveg_n3.py'

  publish-fiveg-n3-lib:
    name: Publish Lib
    needs:
      - publish-charm
      - fiveg-n3-lib-needs-publishing
    if: ${{ github.ref_name == 'main' }}
    uses: canonical/sdcore-github-workflows/.github/workflows/publish-lib.yaml@main
    with:
      lib-name: "charms.sdcore_upf_k8s.v0.fiveg_n3"
    secrets: inherit

  fiveg-n4-lib-needs-publishing:
    runs-on: ubuntu-22.04
    outputs:
      needs-publishing: ${{ steps.changes.outputs.fiveg_n4 }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            fiveg_n4:
              - 'lib/charms/sdcore_upf_k8s/v0/fiveg_n4.py'

  publish-fiveg-n4-lib:
    name: Publish Lib
    needs:
      - publish-charm
      - fiveg-n4-lib-needs-publishing
    if: ${{ github.ref_name == 'main' }}
    uses: canonical/sdcore-github-workflows/.github/workflows/publish-lib.yaml@main
    with:
      lib-name: "charms.sdcore_upf_k8s.v0.fiveg_n4"
    secrets: inherit
